name: "synthetic_identity_both"

data:
  data_set: "synthetic"
  train: "./data/synthetic/train/"
  test: "./data/synthetic/test/"
  num_classes: 2

train:
  batch_size: 128
  num_epochs: 20
  lambda: 0.001
  beta: 0.001
  regularization: "both"
  lr: 0.0001
  batch_frequency_loss: 1

test:
  #mode_forced: "train"
  mode_forced: "test"
  batch_size: 128

model:
  path: "./models/synthetic/"
  name: "model_identity_both"
  save: True
  device: 'cpu' # it could be 'cpu' or 'cuda'
  encoder:
    layer_sizes: [100, 64, 32]
    last_nn_layer: "Identity"  # it could be on from {'Identity', 'Softmax', 'ReLU'}

  decoder:
    layer_sizes: [32, 64, 100]

  input_dim: 100
  latent_dim: 2

tracing:
  show_images: False
  images_to_show: 0
  visualize_latent: True
  batch_frequency: 10
