name: "synthetic_generation"
# Functions
F1:
  amp: 3
  frec: 0.01
  interval: [0, 100]
  shift: 20
  char_to_plot: 'o'
  color_to_plot: 'red'
  train_num_samples: 3000
  test_num_samples: 500

F2:
  amp: 3
  frec: 0.01
  interval: [0, 100]
  shift: 30
  char_to_plot: 'o'
  color_to_plot: 'green'
  train_num_samples: 3000
  test_num_samples: 500

data:
  save: True
  plot: True

  train:
    path: "./data/synthetic/train/"
    normalize: True
  test:
    path: "./data/synthetic/test/"
    normalize: True

  plots:
    path: "./data/synthetic/plots/"


transformation:
  non_linear: sigmoid
  list_dimensions:
    - [10, 2]
    - [50, 10]
    - [100, 50]

