name: "synthetic_generation_clusters"

clusters:
  centers:
    - [-100, -100]
    - [-100, 100]
  std_centers: [10,10]
  dim: 2

data:
  save: True
  plot: True
  normalize: False
  scale: True

  train:
    path: "./data/synthetic_clusters/train/"
    num_samples: 5000
  test:
    path: "./data/synthetic_clusters/test/"
    num_samples: 1000

  plots:
    path: "./data/synthetic_clusters/plots/"

